// Mock seed data for testing
// This can be used to populate initial data in Firestore

import { Post } from '@/types';

export const mockPosts: Omit<Post, 'id'>[] = [
  {
    type: 'experience',
    userId: 'demo-user-1',
    userName: 'Rahul Sharma',
    userCollege: 'IIT Delhi',
    userYear: '2024',
    userLinkedIn: 'https://linkedin.com/in/rahulsharma',
    title: 'Software Engineering Intern at Google',
    content: 'Amazing experience working on Android development. Learned a ton about system design and scalable architectures.',
    company: 'Google',
    jobTitle: 'Software Engineering Intern',
    hasStipend: true,
    stipendAmount: '₹1,00,000/month',
    wasWorthIt: true,
    worthReason: 'Incredible learning experience, great mentorship, and excellent work culture',
    howToCrack: 'Focus on DSA, system design basics, and Android fundamentals. Practice on LeetCode daily.',
    location: 'Bangalore',
    duration: '3 months',
    whatYouGained: 'Deep understanding of Android internals, experience with large codebases, networking skills',
    companyFocus: 'Consumer products, mobile development, user experience',
    expectations: 'Strong coding skills, ability to work independently, good communication',
    projectDone: 'Implemented a new feature in Google Photos that improved load times by 30%',
    tags: ['software', 'android', 'google', 'paid-internship'],
    attachments: [],
    likes: [],
    comments: [],
    shares: 15,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    type: 'experience',
    userId: 'demo-user-2',
    userName: 'Priya Patel',
    userCollege: 'BITS Pilani',
    userYear: '2023',
    title: 'Product Management Intern at Flipkart',
    content: 'Worked on improving the checkout flow. Got to interact with cross-functional teams.',
    company: 'Flipkart',
    jobTitle: 'Product Management Intern',
    hasStipend: true,
    stipendAmount: '₹50,000/month',
    wasWorthIt: true,
    worthReason: 'Great exposure to product thinking and business strategy',
    howToCrack: 'Case studies, product design thinking, understanding of e-commerce metrics',
    location: 'Bangalore',
    duration: '2 months',
    whatYouGained: 'Product strategy, stakeholder management, data analysis',
    companyFocus: 'E-commerce, customer experience, growth',
    expectations: 'Analytical thinking, communication skills, passion for products',
    projectDone: 'Redesigned checkout flow resulting in 8% increase in conversion',
    tags: ['product-management', 'flipkart', 'e-commerce', 'paid-internship'],
    attachments: [],
    likes: [],
    comments: [],
    shares: 8,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    type: 'recruitment',
    userId: 'demo-hr-1',
    userName: 'HR Team - Zomato',
    userCollege: 'Recruiter',
    userYear: 'N/A',
    title: 'Summer Internship 2024 - Software Development',
    content: 'Zomato is hiring Software Development Interns for Summer 2024! Join us in building the future of food tech.',
    company: 'Zomato',
    jobTitle: 'Software Development Intern',
    requirements: 'Strong in DSA, any backend framework (Node.js/Django/Spring), good problem-solving skills',
    applicationLink: 'https://zomato.com/careers/internships',
    location: 'Gurgaon',
    duration: '3 months',
    hasStipend: true,
    stipendAmount: '₹40,000/month',
    tags: ['recruitment', 'software', 'zomato', 'backend', 'paid-internship'],
    attachments: [],
    likes: [],
    comments: [],
    shares: 25,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    type: 'study',
    userId: 'demo-user-3',
    userName: 'Amit Kumar',
    userCollege: 'NIT Trichy',
    userYear: '2022',
    title: 'Google Interview Preparation Guide',
    content: 'Complete guide with questions asked in Google interviews over the past 2 years. Includes DSA, system design, and behavioral questions.',
    company: 'Google',
    subject: 'Interview Preparation',
    tags: ['google', 'interview-prep', 'dsa', 'system-design'],
    attachments: ['https://drive.google.com/file/d/example-google-prep'],
    likes: [],
    comments: [],
    shares: 42,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    type: 'experience',
    userId: 'demo-user-4',
    userName: 'Sneha Reddy',
    userCollege: 'VIT Vellore',
    userYear: '2023',
    title: 'Data Science Intern at Amazon',
    content: 'Worked on recommendation systems for Prime Video. Great learning experience with ML pipelines.',
    company: 'Amazon',
    jobTitle: 'Data Science Intern',
    hasStipend: true,
    stipendAmount: '₹80,000/month',
    wasWorthIt: true,
    worthReason: 'Amazing mentors, real-world ML problems, great pay',
    howToCrack: 'ML fundamentals, Python, SQL, statistics. Build projects and prepare case studies.',
    location: 'Hyderabad',
    duration: '6 months',
    whatYouGained: 'ML pipeline development, A/B testing, working with big data',
    companyFocus: 'Machine learning, recommendation systems, personalization',
    expectations: 'Strong Python, ML basics, SQL proficiency',
    projectDone: 'Built and deployed a recommendation model that improved engagement by 12%',
    tags: ['data-science', 'ml', 'amazon', 'python', 'paid-internship'],
    attachments: [],
    likes: [],
    comments: [],
    shares: 18,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
];

// Demo user credentials
export const DEMO_USER = {
  email: 'test@demo.com',
  password: 'test123',
  name: 'Demo User',
  college: 'Demo College',
  year: '2024',
};
